config/routes.rb
Rails.application.routes.draw do

  get 'transactions/index'

  get 'accounts/index'

  get 'dashboard', to: 'dashboard#index'
  devise_scope :user do
    root :to => 'users/sessions#new'
  end
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  resources :beneficiaries do
    collection do
      get 'all_accounts', to: 'beneficiaries#all_accounts'
    end
  end

  resources :accounts do
    collection do
      post 'recharge_account', to: 'accounts#recharge_account'
    end
  end

  resources :transactions do
    collection do
      get 'update_status', to: 'transactions#update_status'
    end
    member do
      get 'complete_transaction', to: 'transactions#complete_transaction'
      get 'approve_transaction', to: 'transactions#approve_transaction'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @transactions = TransactionService.new({current_user: current_user}).app_wide_transactions
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<%= render '/partials/header' %>
<div class="container-fluid">
  <div class="row">
    <%= render '/partials/sidebar' %>
    <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
      <%=render '/partials/error_messages'%>
      <div class="container">
        <div class="d-flex flex-row justify-content-end">
          <div class="mr-auto p-2"><h2>Transactions </h2></div>
        </div>

      </div>
      <br>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Sender </th>
              <th>Reciever</th>
              <th>Reciever Account</th>
              <th>Amount </th>
              <th>Status </th>
            </tr>
          </thead>
          <tbody>
            <%@transactions.each do |f| %>
              <tr>
                <td><%=f.user.first_name+ '' +f.user.last_name%></td>
                <td><%=reciver_user(f.reciever_user_id)%></td>
                <td><%=reciever_account(f.reciever_account_id)%></td>
                <td><%=f.amount%></td>
                <td><a class="btn btn-sm btn-success" href="<%=approve_transaction_transaction_path(f.id)%>" ><%=f.status%></a></td>

              </tr>
            <%end%>
          </tbody>
        </table>
      </div>

    </main>
  </div>
</div>