config/routes.rb
Rails.application.routes.draw do

  get 'transactions/index'

  get 'accounts/index'

  get 'dashboard', to: 'dashboard#index'
  devise_scope :user do
    root :to => 'users/sessions#new'
  end
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  resources :beneficiaries do
    collection do
      get 'all_accounts', to: 'beneficiaries#all_accounts'
    end
  end

  resources :accounts do
    collection do
      post 'recharge_account', to: 'accounts#recharge_account'
    end
  end

  resources :transactions do
    collection do
      get 'update_status', to: 'transactions#update_status'
    end
    member do
      get 'complete_transaction', to: 'transactions#complete_transaction'
      get 'approve_transaction', to: 'transactions#approve_transaction'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_error_messages.html.erb
<%if flash[:error].present?%>
  <div class="alert alert-danger" role="alert">
    <%=flash.now[:error].html_safe%>
  </div>
<%end%>
<%if flash[:success].present?%>
  <div class="alert alert-success" role="alert">
    <%=flash.now[:success].html_safe%>
  </div>
<%end%>
<%if flash[:alert].present?%>
  <div class="alert alert-warning" role="alert">
    <%=flash.now[:alert].html_safe%>
  </div>
<%end%>
<%if flash[:notice].present?%>
  <div class="alert alert-info" role="alert">
    <%=flash.now[:notice].html_safe%>
  </div>
<%end%>

app/views/partials/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" data-turbolinks="false" href="#">Mini Bank</a>
  </nav>
</header>
<br>
<br>

app/views/partials/_sidebar.html.erb
<nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
  <ul class="nav nav-pills flex-column">
    <%if current_user.role == 'admin'%>
      <li class="nav-item">
        <a style="color:#fff;background-color:#17a2b8;" class="nav-link active" data-turbolinks="false" href="<%=dashboard_path%>">Overview <span class="sr-only">(current)</span></a>
      </li>
    <%end%>
  </ul>

  <ul class="nav nav-pills flex-column">
      <%unless current_user.role == 'admin'%>
        <li class="nav-item">
          <a  class= "nav-link admin-sidebar-link" href="<%=beneficiaries_path%>">Beneficiary</a>
        </li>
        <li class="nav-item">
          <a class="nav-link admin-sidebar-link" href="<%=accounts_path%>">My Accounts</a>
        </li>
        <li class="nav-item">
          <a  class="nav-link admin-sidebar-link"  href="<%=transactions_path%>">Transfer</a>
        </li>
      <%end%>

  </ul>

  <ul class="nav nav-pills flex-column">
    <% if current_user%>
      <li class="nav-item">
        <a class="nav-link btn logout-btn-admin" data-method="Delete" href= "<%=destroy_user_session_path%>"> Log Out</a>
      </li>
    <%end%>
  </ul>
</nav>