config/routes.rb
Rails.application.routes.draw do

  get 'transactions/index'

  get 'accounts/index'

  get 'dashboard', to: 'dashboard#index'
  devise_scope :user do
    root :to => 'users/sessions#new'
  end
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  resources :beneficiaries do
    collection do
      get 'all_accounts', to: 'beneficiaries#all_accounts'
    end
  end

  resources :accounts do
    collection do
      post 'recharge_account', to: 'accounts#recharge_account'
    end
  end

  resources :transactions do
    collection do
      get 'update_status', to: 'transactions#update_status'
    end
    member do
      get 'complete_transaction', to: 'transactions#complete_transaction'
      get 'approve_transaction', to: 'transactions#approve_transaction'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @transactions = TransactionService.new({current_user: current_user}).all_transactions
    #@transactions = TransactionService.new({current_user: current_user}).app_wide_transactions
    @approved_transactions = TransactionService.new({current_user: current_user}).approved_transactions
  end

  def new
    @transaction = Transaction.new
    @current_user_beneficiaries = BeneficiaryService.new({current_user: current_user}).current_user_beneficiaries
    @current_user_accounts = AccountService.new({current_user: current_user}).all_accounts

  end

  def create
    transaction = TransactionService.new({current_user: current_user}).make_transaction(params)
    if transaction
      flash[:success] = "Transaction recorded successfully."
      redirect_path = transactions_path
    else
      flash[:error] = "Transaction failed. Please check your balance or enter valid amount."
      redirect_path = new_transaction_path
    end
    redirect_to redirect_path
  end

  def update_status
    transaction = Transaction.find params[:id]
    transaction.status = "Accepted"
    transaction.save!
    render json: {status: transaction.status}
  end

  def complete_transaction
    transaction = Transaction.find params[:id]
    b_account_id  = transaction.reciever_account_id
    b_user_id = transaction.reciever_user_id
    sender = transaction.user
    Account.where(id: b_account_id).first
    User.where(id: b_user_id).first
    UserAccount.where(user_id: b_user_id, account_id: b_account_id).first
    transaction.status = "Accepted"
    transaction.save!
    redirect_to accounts_path
  end

  def approve_transaction
    transaction = Transaction.find params[:id]
    b_account_id  = transaction.reciever_account_id
    b_user_id = transaction.reciever_user_id
    sender = transaction.user
    Account.where(id: b_account_id).first
    User.where(id: b_user_id).first
    UserAccount.where(user_id: b_user_id, account_id: b_account_id).first
    transaction.status = "Accepted"
    transaction.save!
    redirect_to dashboard_path
  end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def reciver_user id
    user = User.find id
    user.first_name+''+user.last_name
  end
  def reciever_account id
    account = Account.find id
    account.title
  end
end

app/views/transactions/index.html.erb
<%= render '/partials/header' %>
<div class="container-fluid">
  <div class="row">
    <%= render '/partials/sidebar' %>
    <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
      <%=render '/partials/error_messages'%>
      <div class="container">
        <div class="d-flex flex-row justify-content-end">
          <div class="mr-auto p-2"><h2>Transactions </h2></div>
          <div class="p-2"><a class="btn btn-success float-right" href="<%=new_transaction_path%>">Make A Transaction</a></div>
        </div>

      </div>
      <br>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Sender </th>
              <th>Reciever</th>
              <th>Reciever Account</th>
              <th>Amount </th>
              <th>Status </th>
            </tr>
          </thead>
          <tbody>
            <%@transactions.each do |f| %>
              <tr>
                <td><%=f.user.first_name+ '' +f.user.last_name%></td>
                <td><%=reciver_user(f.reciever_user_id)%></td>
                <td><%=reciever_account(f.reciever_account_id)%></td>
                <td><%=f.amount%></td>
                <td><a class="btn btn-sm disable-btn btn-success" href="<%=complete_transaction_transaction_path(f.id)%>" ><%=f.status%></a></td>

              </tr>
            <%end%>
          </tbody>
        </table>
      </div>
      <div class="container">
        <div class="d-flex flex-row justify-content-end">
          <div class="mr-auto p-2"><h2>Approved Transactions </h2></div>
        </div>
      </div>
      <br>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Sender </th>
              <th>Reciever</th>
              <th>Reciever Account</th>
              <th>Amount </th>
              <th>Status </th>
            </tr>
          </thead>
          <tbody>
            <%@approved_transactions.each do |f| %>
              <tr>
                <td><%=f.user.first_name+ '' +f.user.last_name%></td>
                <td><%=reciver_user(f.reciever_user_id)%></td>
                <td><%=reciever_account(f.reciever_account_id)%></td>
                <td><%=f.amount%></td>
                <td><a class="btn btn-sm disable-btn btn-success" href="<%=complete_transaction_transaction_path(f.id)%>" ><%=f.status%></a></td>

              </tr>
            <%end%>
          </tbody>
        </table>
      </div>



    </main>
  </div>
</div>

app/views/transactions/new.html.erb
<%= render '/partials/header' %>
<div class="container-fluid">
  <div class="row">
    <%= render '/partials/header' %>
    <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
      <h2>Make-a-Transaction</h2>
      <%=render '/partials/error_messages'%>
      <div class="container">
        <%= form_for @transaction,url: transactions_path,method:'Post',html:{class:'form'} do |f|%>
          <div class="form-group row">
            <label for="first_name" class="col-sm-2 col-form-label">Sender User Account:</label>
            <div class="col-sm-10">
              <select name="sender_account_id" class="custom-select" id= "sender_account_id">
                <option>Please select account</option>
                <% @current_user_accounts.each do |b|%>
                  <option value="<%=b[1]%>"><%=b[0]%></option>
                <%end%>
              </select>
            </div>
          </div>

          <div class="form-group row">
            <label for="first_name" class="col-sm-2 col-form-label">Benefactor User:</label>
            <div class="col-sm-10">
              <select name="reciever_user_id" class="custom-select" id= "reciever_user_id">
                <option>Please select account</option>
                <% @current_user_beneficiaries.each do |b|%>
                  <option value="<%=b[1]%>"><%=b[0]%></option>
                <%end%>
              </select>
            </div>
          </div>

          <div class="form-group row">
            <label for="first_name" class="col-sm-2 col-form-label">Beneficiary Account</label>
            <div class="col-sm-10">
              <select name="reciever_account_id" class="custom-select" id= "reciever_account_id">
                <option>Please select account</option>
              </select>
            </div>
          </div>


          <div class="form-group row">
            <label for="first_name" class="col-sm-2 col-form-label">Amount:</label>
            <div class="col-sm-10">
              <input class="form-control" type="text" name="amount">
            </div>
          </div>



          <div class="form-group row">
            <div class="offset-sm-2 col-sm-10">
              <button type="submit" class="btn btn-primary btn-success">Create</button>
            </div>
          </div>
        <%end%>
      </div>
    </main>
  </div>
</div>