config/routes.rb
Rails.application.routes.draw do

  get 'transactions/index'

  get 'accounts/index'

  get 'dashboard', to: 'dashboard#index'
  devise_scope :user do
    root :to => 'users/sessions#new'
  end
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  resources :beneficiaries do
    collection do
      get 'all_accounts', to: 'beneficiaries#all_accounts'
    end
  end

  resources :accounts do
    collection do
      post 'recharge_account', to: 'accounts#recharge_account'
    end
  end

  resources :transactions do
    collection do
      get 'update_status', to: 'transactions#update_status'
    end
    member do
      get 'complete_transaction', to: 'transactions#complete_transaction'
      get 'approve_transaction', to: 'transactions#approve_transaction'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :user_accounts
  has_many :users, through: :user_accounts
  has_many :beneficiaries

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def index
    @result = []
    @accounts = current_user.accounts
    transactions = current_user.transactions.where(status: 'Accepted') if current_user.transactions.present?
    if transactions.present?
      transactions.each do |r|
        sender_account_id = r[:sender_account_id]
        reciever_account_id = r[:reciever_account_id]
        reciever_user_id = r[:reciever_user_id]
        amount = r[:amount]
        r[:status] = ''
        r.save!
        reciever = User.find reciever_user_id
        reciever_account = reciever.accounts.where(id: reciever_account_id).first
        sender_account = current_user.accounts.where(id: sender_account_id).first
        if reciever_account.balance.present?
          reciever_account.balance = reciever_account.balance + amount.to_f
        else
          reciever_account.balance = 0.0
          reciever_account.balance = reciever_account.balance + amount.to_f
        end
        if sender_account.balance.present?
          sender_account.balance = sender_account.balance - amount.to_f
        else
          sender_account.balance = 0.0
          sender_account.balance = sender_account.balance - amount.to_f
        end
        sender_account.save!; reciever_account.save!
      end
    end
  end

  def new
    @account = Account.new
    @all_accounts = AccountService.new({current_user: current_user}).all_accounts
  end

  def recharge_account
    recharge_account = AccountService.new({current_user: current_user}).recharge_account(account_params)
    if recharge_account
      flash[:success] = "Account Recharged successfully."
      redirect_path = accounts_path
    else
      flash[:success] = "Amount you entered is invalid."
      redirect_path = new_account_path
    end
    redirect_to redirect_path
  end

  private
    def account_params
      params.require(:account).permit(:balance, :id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/index.html.erb
<%= render '/partials/header' %>
<div class="container-fluid">
  <div class="row">
    <%= render '/partials/sidebar' %>
    <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
      <%=render '/partials/error_messages'%>
      <div class="container">
        <div class="d-flex flex-row justify-content-end">
          <div class="mr-auto p-2"><h2>My Accounts </h2></div>
          <div class="p-2"><a class="btn btn-success float-right" href="<%=new_account_path%>">Top-Up Account</a></div>
        </div>

      </div>
      <br>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Title</th>
              <th>Balance</th>

            </tr>
          </thead>
          <tbody>
            <%@accounts.each do |f|%>
              <tr>
                <td><%=f.title%></td>
                <td><%=f.balance%></td>
              </tr>
            <%end%>
          </tbody>
        </table>
      </div>

    </main>
  </div>
</div>

app/views/accounts/new.html.erb
<%= render '/partials/header' %>
<div class="container-fluid">
  <div class="row">
    <%= render '/partials/header' %>
    <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
      <h2>Top_Up Account</h2>
      <%=render '/partials/error_messages'%>
      <div class="container">
        <%= form_for @account,url: recharge_account_accounts_path,method:'Post',html:{class:'form'} do |f|%>

          <div class="form-group row">
            <label for="first_name" class="col-sm-2 col-form-label">Account:</label>
            <div class="col-sm-10">
              <%=f.select :id, options_for_select(@all_accounts),{include_blank: 'Please select your account.'},class:'custom-select'%>
            </div>
          </div>

          <div class="form-group row">
            <label for="first_name" class="col-sm-2 col-form-label">Amount:</label>
            <div class="col-sm-10">
              <%=f.text_field :balance, class:'form-control'%>
            </div>
          </div>



          <div class="form-group row">
            <div class="offset-sm-2 col-sm-10">
              <button type="submit" class="btn btn-primary btn-success">Create</button>
            </div>
          </div>
        <%end%>
      </div>
    </main>
  </div>
</div>